[project]
name = "auto-workflows-ships"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dash>=3.0.4",
    "pandas>=2.2.3",
    "plotly>=6.0.1",
    "tqdm>=4.67.1",
]
